apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-the-counter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-the-counter
subjects:
- kind: ServiceAccount
  name: sa-the-counter
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: the-counter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]